// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.5.0
// source: grpc/tradeapi/v1/side/side.proto

package side

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сторона сделки
type Side int32

const (
	// Сторона сделки не указана
	Side_SIDE_UNSPECIFIED Side = 0
	// Покупка
	Side_SIDE_BUY Side = 1
	// Продажа
	Side_SIDE_SELL Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_side_side_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_side_side_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_side_side_proto_rawDescGZIP(), []int{0}
}

var File_grpc_tradeapi_v1_side_side_proto protoreflect.FileDescriptor

var file_grpc_tradeapi_v1_side_side_proto_rawDesc = []byte{
	0x0a, 0x20, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x69, 0x64, 0x65, 0x2f, 0x73, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2a, 0x39, 0x0a, 0x04, 0x53, 0x69, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x10,
	0x53, 0x49, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x49, 0x44, 0x45, 0x5f, 0x42, 0x55, 0x59, 0x10, 0x01,
	0x12, 0x0d, 0x0a, 0x09, 0x53, 0x49, 0x44, 0x45, 0x5f, 0x53, 0x45, 0x4c, 0x4c, 0x10, 0x02, 0x42,
	0x1f, 0x50, 0x01, 0x5a, 0x1b, 0x66, 0x69, 0x6e, 0x61, 0x6d, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69, 0x64, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_tradeapi_v1_side_side_proto_rawDescOnce sync.Once
	file_grpc_tradeapi_v1_side_side_proto_rawDescData = file_grpc_tradeapi_v1_side_side_proto_rawDesc
)

func file_grpc_tradeapi_v1_side_side_proto_rawDescGZIP() []byte {
	file_grpc_tradeapi_v1_side_side_proto_rawDescOnce.Do(func() {
		file_grpc_tradeapi_v1_side_side_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_tradeapi_v1_side_side_proto_rawDescData)
	})
	return file_grpc_tradeapi_v1_side_side_proto_rawDescData
}

var file_grpc_tradeapi_v1_side_side_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_tradeapi_v1_side_side_proto_goTypes = []interface{}{
	(Side)(0), // 0: grpc.tradeapi.v1.Side
}
var file_grpc_tradeapi_v1_side_side_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_tradeapi_v1_side_side_proto_init() }
func file_grpc_tradeapi_v1_side_side_proto_init() {
	if File_grpc_tradeapi_v1_side_side_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_tradeapi_v1_side_side_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_tradeapi_v1_side_side_proto_goTypes,
		DependencyIndexes: file_grpc_tradeapi_v1_side_side_proto_depIdxs,
		EnumInfos:         file_grpc_tradeapi_v1_side_side_proto_enumTypes,
	}.Build()
	File_grpc_tradeapi_v1_side_side_proto = out.File
	file_grpc_tradeapi_v1_side_side_proto_rawDesc = nil
	file_grpc_tradeapi_v1_side_side_proto_goTypes = nil
	file_grpc_tradeapi_v1_side_side_proto_depIdxs = nil
}
