proto_gen:
	protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative grpc/tradeapi/v1/side/side.proto grpc/tradeapi/v1/accounts/accounts_service.proto grpc/tradeapi/v1/assets/assets_service.proto grpc/tradeapi/v1/auth/auth_service.proto grpc/tradeapi/v1/orders/orders_service.proto  grpc/tradeapi/v1/marketdata/marketdata_service.proto
