// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.5.0
// source: grpc/tradeapi/v1/assets/assets_service.proto

package assets_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	interval "google.golang.org/genproto/googleapis/type/interval"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип опциона
type Option_Type int32

const (
	// Неопределенное значение
	Option_TYPE_UNSPECIFIED Option_Type = 0
	// Колл
	Option_TYPE_CALL Option_Type = 1
	// Пут
	Option_TYPE_PUT Option_Type = 2
)

// Enum value maps for Option_Type.
var (
	Option_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_CALL",
		2: "TYPE_PUT",
	}
	Option_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_CALL":        1,
		"TYPE_PUT":         2,
	}
)

func (x Option_Type) Enum() *Option_Type {
	p := new(Option_Type)
	*p = x
	return p
}

func (x Option_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Option_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[0].Descriptor()
}

func (Option_Type) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[0]
}

func (x Option_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Option_Type.Descriptor instead.
func (Option_Type) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{12, 0}
}

// Статус
type Longable_Status int32

const (
	// Не доступен
	Longable_NOT_AVAILABLE Longable_Status = 0
	// Доступен
	Longable_AVAILABLE Longable_Status = 1
	// Запрещено на уровне счета
	Longable_ACCOUNT_NOT_APPROVED Longable_Status = 2
)

// Enum value maps for Longable_Status.
var (
	Longable_Status_name = map[int32]string{
		0: "NOT_AVAILABLE",
		1: "AVAILABLE",
		2: "ACCOUNT_NOT_APPROVED",
	}
	Longable_Status_value = map[string]int32{
		"NOT_AVAILABLE":        0,
		"AVAILABLE":            1,
		"ACCOUNT_NOT_APPROVED": 2,
	}
)

func (x Longable_Status) Enum() *Longable_Status {
	p := new(Longable_Status)
	*p = x
	return p
}

func (x Longable_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Longable_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[1].Descriptor()
}

func (Longable_Status) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[1]
}

func (x Longable_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Longable_Status.Descriptor instead.
func (Longable_Status) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{13, 0}
}

// Статус
type Shortable_Status int32

const (
	// Не доступен
	Shortable_NOT_AVAILABLE Shortable_Status = 0
	// Доступен
	Shortable_AVAILABLE Shortable_Status = 1
	// Признак того, что бумага Hard To Borrow (если есть)
	Shortable_HTB Shortable_Status = 2
	// Запрещено на уровне счета
	Shortable_ACCOUNT_NOT_APPROVED Shortable_Status = 3
	// Разрешено в составе стратегии
	Shortable_AVAILABLE_STRATEGY Shortable_Status = 4
)

// Enum value maps for Shortable_Status.
var (
	Shortable_Status_name = map[int32]string{
		0: "NOT_AVAILABLE",
		1: "AVAILABLE",
		2: "HTB",
		3: "ACCOUNT_NOT_APPROVED",
		4: "AVAILABLE_STRATEGY",
	}
	Shortable_Status_value = map[string]int32{
		"NOT_AVAILABLE":        0,
		"AVAILABLE":            1,
		"HTB":                  2,
		"ACCOUNT_NOT_APPROVED": 3,
		"AVAILABLE_STRATEGY":   4,
	}
)

func (x Shortable_Status) Enum() *Shortable_Status {
	p := new(Shortable_Status)
	*p = x
	return p
}

func (x Shortable_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Shortable_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[2].Descriptor()
}

func (Shortable_Status) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[2]
}

func (x Shortable_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Shortable_Status.Descriptor instead.
func (Shortable_Status) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{14, 0}
}

// Запрос получения списка доступных бирж
type ExchangesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExchangesRequest) Reset() {
	*x = ExchangesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangesRequest) ProtoMessage() {}

func (x *ExchangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangesRequest.ProtoReflect.Descriptor instead.
func (*ExchangesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{0}
}

// Список доступных бирж
type ExchangesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Информация о бирже
	Exchanges []*Exchange `protobuf:"bytes,1,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
}

func (x *ExchangesResponse) Reset() {
	*x = ExchangesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangesResponse) ProtoMessage() {}

func (x *ExchangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangesResponse.ProtoReflect.Descriptor instead.
func (*ExchangesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangesResponse) GetExchanges() []*Exchange {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

// Запрос получения списка доступных инструментов
type AssetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AssetsRequest) Reset() {
	*x = AssetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetsRequest) ProtoMessage() {}

func (x *AssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetsRequest.ProtoReflect.Descriptor instead.
func (*AssetsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{2}
}

// Список доступных инструментов
type AssetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Информация об инструменте
	Assets []*Asset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
}

func (x *AssetsResponse) Reset() {
	*x = AssetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetsResponse) ProtoMessage() {}

func (x *AssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetsResponse.ProtoReflect.Descriptor instead.
func (*AssetsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{3}
}

func (x *AssetsResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

// Запрос торговых параметров инструмента
type GetAssetParamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Символ инструмента
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// ID аккаунта для которого будут подбираться торговые параметры
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *GetAssetParamsRequest) Reset() {
	*x = GetAssetParamsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetParamsRequest) ProtoMessage() {}

func (x *GetAssetParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetParamsRequest.ProtoReflect.Descriptor instead.
func (*GetAssetParamsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAssetParamsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetAssetParamsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// Торговые параметры инструмента
type GetAssetParamsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Символ инструмента
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// ID аккаунта для которого подбираются торговые параметры
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Доступны ли торговые операции
	Tradeable bool `protobuf:"varint,3,opt,name=tradeable,proto3" json:"tradeable,omitempty"`
	// Доступны ли операции в Лонг
	Longable *Longable `protobuf:"bytes,4,opt,name=longable,proto3" json:"longable,omitempty"`
	// Доступны ли операции в Шорт
	Shortable *Shortable `protobuf:"bytes,5,opt,name=shortable,proto3" json:"shortable,omitempty"`
	// Ставка риска для операции в Лонг
	LongRiskRate *decimal.Decimal `protobuf:"bytes,6,opt,name=long_risk_rate,json=longRiskRate,proto3" json:"long_risk_rate,omitempty"`
	// Сумма обеспечения для поддержания позиции Лонг
	LongCollateral *money.Money `protobuf:"bytes,7,opt,name=long_collateral,json=longCollateral,proto3" json:"long_collateral,omitempty"`
	// Ставка риска для операции в Шорт
	ShortRiskRate *decimal.Decimal `protobuf:"bytes,8,opt,name=short_risk_rate,json=shortRiskRate,proto3" json:"short_risk_rate,omitempty"`
	// Сумма обеспечения для поддержания позиции Шорт
	ShortCollateral *money.Money `protobuf:"bytes,9,opt,name=short_collateral,json=shortCollateral,proto3" json:"short_collateral,omitempty"`
}

func (x *GetAssetParamsResponse) Reset() {
	*x = GetAssetParamsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetParamsResponse) ProtoMessage() {}

func (x *GetAssetParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetParamsResponse.ProtoReflect.Descriptor instead.
func (*GetAssetParamsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAssetParamsResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetAssetParamsResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAssetParamsResponse) GetTradeable() bool {
	if x != nil {
		return x.Tradeable
	}
	return false
}

func (x *GetAssetParamsResponse) GetLongable() *Longable {
	if x != nil {
		return x.Longable
	}
	return nil
}

func (x *GetAssetParamsResponse) GetShortable() *Shortable {
	if x != nil {
		return x.Shortable
	}
	return nil
}

func (x *GetAssetParamsResponse) GetLongRiskRate() *decimal.Decimal {
	if x != nil {
		return x.LongRiskRate
	}
	return nil
}

func (x *GetAssetParamsResponse) GetLongCollateral() *money.Money {
	if x != nil {
		return x.LongCollateral
	}
	return nil
}

func (x *GetAssetParamsResponse) GetShortRiskRate() *decimal.Decimal {
	if x != nil {
		return x.ShortRiskRate
	}
	return nil
}

func (x *GetAssetParamsResponse) GetShortCollateral() *money.Money {
	if x != nil {
		return x.ShortCollateral
	}
	return nil
}

// Запрос получения цепочки опционов
type OptionsChainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Символ базового актива опциона
	UnderlyingSymbol string `protobuf:"bytes,1,opt,name=underlying_symbol,json=underlyingSymbol,proto3" json:"underlying_symbol,omitempty"`
}

func (x *OptionsChainRequest) Reset() {
	*x = OptionsChainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionsChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsChainRequest) ProtoMessage() {}

func (x *OptionsChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionsChainRequest.ProtoReflect.Descriptor instead.
func (*OptionsChainRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{6}
}

func (x *OptionsChainRequest) GetUnderlyingSymbol() string {
	if x != nil {
		return x.UnderlyingSymbol
	}
	return ""
}

// Информация о цепочке опционов
type OptionsChainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Символ опциона
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Информация об опционе
	Options []*Option `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *OptionsChainResponse) Reset() {
	*x = OptionsChainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionsChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsChainResponse) ProtoMessage() {}

func (x *OptionsChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionsChainResponse.ProtoReflect.Descriptor instead.
func (*OptionsChainResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{7}
}

func (x *OptionsChainResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OptionsChainResponse) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

// Запрос получения расписания инструмента
type ScheduleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Символ инструмента
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{8}
}

func (x *ScheduleRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Расписание инструмента
type ScheduleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Символ инструмента
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Сессии инструмента
	Sessions []*ScheduleResponse_Sessions `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"`
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{9}
}

func (x *ScheduleResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ScheduleResponse) GetSessions() []*ScheduleResponse_Sessions {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// Информация о бирже
type Exchange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Идентификатор биржи mic
	Mic string `protobuf:"bytes,1,opt,name=mic,proto3" json:"mic,omitempty"`
	// Наименование биржи
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Exchange) Reset() {
	*x = Exchange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exchange) ProtoMessage() {}

func (x *Exchange) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exchange.ProtoReflect.Descriptor instead.
func (*Exchange) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{10}
}

func (x *Exchange) GetMic() string {
	if x != nil {
		return x.Mic
	}
	return ""
}

func (x *Exchange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Информация об инструменте
type Asset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Символ инструмента ticker@mic
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Идентификатор инструмента
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Тикер инструмента
	Ticker string `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	// mic идентификатор биржи
	Mic string `protobuf:"bytes,4,opt,name=mic,proto3" json:"mic,omitempty"`
	// Isin идентификатор инструмента
	Isin string `protobuf:"bytes,5,opt,name=isin,proto3" json:"isin,omitempty"`
	// Тип инструмента
	Type string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	// Наименование инструмента
	Name string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Asset) Reset() {
	*x = Asset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{11}
}

func (x *Asset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Asset) GetMic() string {
	if x != nil {
		return x.Mic
	}
	return ""
}

func (x *Asset) GetIsin() string {
	if x != nil {
		return x.Isin
	}
	return ""
}

func (x *Asset) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Информация об опционе
type Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Символ инструмента
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Тип инструмента
	Type Option_Type `protobuf:"varint,2,opt,name=type,proto3,enum=grpc.tradeapi.v1.assets.Option_Type" json:"type,omitempty"`
	// Лот, количество базового актива в инструменте
	ContractSize *decimal.Decimal `protobuf:"bytes,4,opt,name=contract_size,json=contractSize,proto3" json:"contract_size,omitempty"`
	// Дата начала торговли
	TradeFirstDay *date.Date `protobuf:"bytes,5,opt,name=trade_first_day,json=tradeFirstDay,proto3" json:"trade_first_day,omitempty"`
	// Дата экспирации
	TradeLastDay *date.Date `protobuf:"bytes,6,opt,name=trade_last_day,json=tradeLastDay,proto3" json:"trade_last_day,omitempty"`
	// Цена исполнения опциона
	Strike *decimal.Decimal `protobuf:"bytes,7,opt,name=strike,proto3" json:"strike,omitempty"`
	// Множитель опциона
	Multiplier *decimal.Decimal `protobuf:"bytes,9,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
}

func (x *Option) Reset() {
	*x = Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{12}
}

func (x *Option) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Option) GetType() Option_Type {
	if x != nil {
		return x.Type
	}
	return Option_TYPE_UNSPECIFIED
}

func (x *Option) GetContractSize() *decimal.Decimal {
	if x != nil {
		return x.ContractSize
	}
	return nil
}

func (x *Option) GetTradeFirstDay() *date.Date {
	if x != nil {
		return x.TradeFirstDay
	}
	return nil
}

func (x *Option) GetTradeLastDay() *date.Date {
	if x != nil {
		return x.TradeLastDay
	}
	return nil
}

func (x *Option) GetStrike() *decimal.Decimal {
	if x != nil {
		return x.Strike
	}
	return nil
}

func (x *Option) GetMultiplier() *decimal.Decimal {
	if x != nil {
		return x.Multiplier
	}
	return nil
}

// Доступны ли операции в Лонг
type Longable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Статус инструмента
	Value Longable_Status `protobuf:"varint,1,opt,name=value,proto3,enum=grpc.tradeapi.v1.assets.Longable_Status" json:"value,omitempty"`
	// Сколько дней действует запрет на операции в Лонг (если есть)
	HaltedDays int32 `protobuf:"varint,2,opt,name=halted_days,json=haltedDays,proto3" json:"halted_days,omitempty"`
}

func (x *Longable) Reset() {
	*x = Longable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Longable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Longable) ProtoMessage() {}

func (x *Longable) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Longable.ProtoReflect.Descriptor instead.
func (*Longable) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{13}
}

func (x *Longable) GetValue() Longable_Status {
	if x != nil {
		return x.Value
	}
	return Longable_NOT_AVAILABLE
}

func (x *Longable) GetHaltedDays() int32 {
	if x != nil {
		return x.HaltedDays
	}
	return 0
}

// Доступны ли операции в Шорт
type Shortable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Статус инструмента
	Value Shortable_Status `protobuf:"varint,1,opt,name=value,proto3,enum=grpc.tradeapi.v1.assets.Shortable_Status" json:"value,omitempty"`
	// Сколько дней действует запрет на операции в Шорт (если есть)
	HaltedDays int32 `protobuf:"varint,2,opt,name=halted_days,json=haltedDays,proto3" json:"halted_days,omitempty"`
}

func (x *Shortable) Reset() {
	*x = Shortable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shortable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shortable) ProtoMessage() {}

func (x *Shortable) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shortable.ProtoReflect.Descriptor instead.
func (*Shortable) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{14}
}

func (x *Shortable) GetValue() Shortable_Status {
	if x != nil {
		return x.Value
	}
	return Shortable_NOT_AVAILABLE
}

func (x *Shortable) GetHaltedDays() int32 {
	if x != nil {
		return x.HaltedDays
	}
	return 0
}

// Сессии
type ScheduleResponse_Sessions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Тип сессии
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Интервал сессии
	Interval *interval.Interval `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *ScheduleResponse_Sessions) Reset() {
	*x = ScheduleResponse_Sessions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleResponse_Sessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse_Sessions) ProtoMessage() {}

func (x *ScheduleResponse_Sessions) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse_Sessions.ProtoReflect.Descriptor instead.
func (*ScheduleResponse_Sessions) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ScheduleResponse_Sessions) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScheduleResponse_Sessions) GetInterval() *interval.Interval {
	if x != nil {
		return x.Interval
	}
	return nil
}

var File_grpc_tradeapi_v1_assets_assets_service_proto protoreflect.FileDescriptor

var file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x64, 0x65, 0x63, 0x69, 0x6d,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x12, 0x0a,
	0x10, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x54, 0x0a, 0x11, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x09, 0x65, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x0e, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x22, 0x4e, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x22, 0xe4, 0x03, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x6c, 0x6f, 0x6e, 0x67, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64,
	0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x4c,
	0x6f, 0x6e, 0x67, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x08, 0x6c, 0x6f, 0x6e, 0x67, 0x61, 0x62, 0x6c,
	0x65, 0x12, 0x40, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64,
	0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x3a, 0x0a, 0x0e, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x72, 0x69, 0x73, 0x6b,
	0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61,
	0x6c, 0x52, 0x0c, 0x6c, 0x6f, 0x6e, 0x67, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x61, 0x74, 0x65, 0x12,
	0x3b, 0x0a, 0x0f, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x72,
	0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x0e, 0x6c, 0x6f,
	0x6e, 0x67, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x3c, 0x0a, 0x0f,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x72, 0x69, 0x73, 0x6b, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x0d, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x61, 0x74, 0x65, 0x12, 0x3d, 0x0a, 0x10, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x0f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x43,
	0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x22, 0x42, 0x0a, 0x13, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2b, 0x0a, 0x11, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x6c, 0x79, 0x69, 0x6e, 0x67, 0x5f, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x75, 0x6e, 0x64,
	0x65, 0x72, 0x6c, 0x79, 0x69, 0x6e, 0x67, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x69, 0x0a,
	0x14, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x39, 0x0a,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x29, 0x0a, 0x0f, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x22, 0xcd, 0x01, 0x0a, 0x10, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x4e, 0x0a, 0x08, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x32, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x08, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x1a, 0x51, 0x0a, 0x08, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x31, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x22, 0x30, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69,
	0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69,
	0x63, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x69, 0x73, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xa8, 0x03,
	0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x0d, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x39, 0x0a, 0x0f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x44, 0x61, 0x74,
	0x65, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x64, 0x65, 0x46, 0x69, 0x72, 0x73, 0x74, 0x44, 0x61, 0x79,
	0x12, 0x37, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x64,
	0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x74, 0x72, 0x61,
	0x64, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x44, 0x61, 0x79, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x72,
	0x69, 0x6b, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x52,
	0x06, 0x73, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61,
	0x6c, 0x52, 0x0a, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x22, 0x39, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x43, 0x41, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x50, 0x55, 0x54, 0x10, 0x02, 0x22, 0xb1, 0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x6e,
	0x67, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64,
	0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x4c,
	0x6f, 0x6e, 0x67, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x61, 0x6c, 0x74, 0x65, 0x64, 0x5f,
	0x64, 0x61, 0x79, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x68, 0x61, 0x6c, 0x74,
	0x65, 0x64, 0x44, 0x61, 0x79, 0x73, 0x22, 0x44, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c,
	0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45,
	0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4e, 0x4f,
	0x54, 0x5f, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x02, 0x22, 0xd4, 0x01, 0x0a,
	0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x3f, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x68,
	0x61, 0x6c, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x68, 0x61, 0x6c, 0x74, 0x65, 0x64, 0x44, 0x61, 0x79, 0x73, 0x22, 0x65, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x56,
	0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x56, 0x41,
	0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x48, 0x54, 0x42, 0x10,
	0x02, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x41,
	0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x52, 0x41, 0x54, 0x45, 0x47,
	0x59, 0x10, 0x04, 0x32, 0xb7, 0x05, 0x0a, 0x0d, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x79, 0x0a, 0x09, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x73, 0x12, 0x29, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x45, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73,
	0x12, 0x6d, 0x0a, 0x06, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x26, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0c, 0x12, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12,
	0x95, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x2e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x12, 0x1a, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x7b, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x7d,
	0x2f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x9b, 0x01, 0x0a, 0x0c, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x2c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72,
	0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73,
	0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x28, 0x12, 0x26, 0x2f,
	0x76, 0x31, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x7b, 0x75, 0x6e, 0x64, 0x65, 0x72,
	0x6c, 0x79, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x7d, 0x2f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x85, 0x01, 0x0a, 0x08, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x12, 0x28, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x12,
	0x1c, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x7b, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x7d, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x42, 0x26, 0x50,
	0x01, 0x5a, 0x22, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescOnce sync.Once
	file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescData = file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc
)

func file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP() []byte {
	file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescOnce.Do(func() {
		file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescData)
	})
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescData
}

var file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_grpc_tradeapi_v1_assets_assets_service_proto_goTypes = []interface{}{
	(Option_Type)(0),                  // 0: grpc.tradeapi.v1.assets.Option.Type
	(Longable_Status)(0),              // 1: grpc.tradeapi.v1.assets.Longable.Status
	(Shortable_Status)(0),             // 2: grpc.tradeapi.v1.assets.Shortable.Status
	(*ExchangesRequest)(nil),          // 3: grpc.tradeapi.v1.assets.ExchangesRequest
	(*ExchangesResponse)(nil),         // 4: grpc.tradeapi.v1.assets.ExchangesResponse
	(*AssetsRequest)(nil),             // 5: grpc.tradeapi.v1.assets.AssetsRequest
	(*AssetsResponse)(nil),            // 6: grpc.tradeapi.v1.assets.AssetsResponse
	(*GetAssetParamsRequest)(nil),     // 7: grpc.tradeapi.v1.assets.GetAssetParamsRequest
	(*GetAssetParamsResponse)(nil),    // 8: grpc.tradeapi.v1.assets.GetAssetParamsResponse
	(*OptionsChainRequest)(nil),       // 9: grpc.tradeapi.v1.assets.OptionsChainRequest
	(*OptionsChainResponse)(nil),      // 10: grpc.tradeapi.v1.assets.OptionsChainResponse
	(*ScheduleRequest)(nil),           // 11: grpc.tradeapi.v1.assets.ScheduleRequest
	(*ScheduleResponse)(nil),          // 12: grpc.tradeapi.v1.assets.ScheduleResponse
	(*Exchange)(nil),                  // 13: grpc.tradeapi.v1.assets.Exchange
	(*Asset)(nil),                     // 14: grpc.tradeapi.v1.assets.Asset
	(*Option)(nil),                    // 15: grpc.tradeapi.v1.assets.Option
	(*Longable)(nil),                  // 16: grpc.tradeapi.v1.assets.Longable
	(*Shortable)(nil),                 // 17: grpc.tradeapi.v1.assets.Shortable
	(*ScheduleResponse_Sessions)(nil), // 18: grpc.tradeapi.v1.assets.ScheduleResponse.Sessions
	(*decimal.Decimal)(nil),           // 19: google.type.Decimal
	(*money.Money)(nil),               // 20: google.type.Money
	(*date.Date)(nil),                 // 21: google.type.Date
	(*interval.Interval)(nil),         // 22: google.type.Interval
}
var file_grpc_tradeapi_v1_assets_assets_service_proto_depIdxs = []int32{
	13, // 0: grpc.tradeapi.v1.assets.ExchangesResponse.exchanges:type_name -> grpc.tradeapi.v1.assets.Exchange
	14, // 1: grpc.tradeapi.v1.assets.AssetsResponse.assets:type_name -> grpc.tradeapi.v1.assets.Asset
	16, // 2: grpc.tradeapi.v1.assets.GetAssetParamsResponse.longable:type_name -> grpc.tradeapi.v1.assets.Longable
	17, // 3: grpc.tradeapi.v1.assets.GetAssetParamsResponse.shortable:type_name -> grpc.tradeapi.v1.assets.Shortable
	19, // 4: grpc.tradeapi.v1.assets.GetAssetParamsResponse.long_risk_rate:type_name -> google.type.Decimal
	20, // 5: grpc.tradeapi.v1.assets.GetAssetParamsResponse.long_collateral:type_name -> google.type.Money
	19, // 6: grpc.tradeapi.v1.assets.GetAssetParamsResponse.short_risk_rate:type_name -> google.type.Decimal
	20, // 7: grpc.tradeapi.v1.assets.GetAssetParamsResponse.short_collateral:type_name -> google.type.Money
	15, // 8: grpc.tradeapi.v1.assets.OptionsChainResponse.options:type_name -> grpc.tradeapi.v1.assets.Option
	18, // 9: grpc.tradeapi.v1.assets.ScheduleResponse.sessions:type_name -> grpc.tradeapi.v1.assets.ScheduleResponse.Sessions
	0,  // 10: grpc.tradeapi.v1.assets.Option.type:type_name -> grpc.tradeapi.v1.assets.Option.Type
	19, // 11: grpc.tradeapi.v1.assets.Option.contract_size:type_name -> google.type.Decimal
	21, // 12: grpc.tradeapi.v1.assets.Option.trade_first_day:type_name -> google.type.Date
	21, // 13: grpc.tradeapi.v1.assets.Option.trade_last_day:type_name -> google.type.Date
	19, // 14: grpc.tradeapi.v1.assets.Option.strike:type_name -> google.type.Decimal
	19, // 15: grpc.tradeapi.v1.assets.Option.multiplier:type_name -> google.type.Decimal
	1,  // 16: grpc.tradeapi.v1.assets.Longable.value:type_name -> grpc.tradeapi.v1.assets.Longable.Status
	2,  // 17: grpc.tradeapi.v1.assets.Shortable.value:type_name -> grpc.tradeapi.v1.assets.Shortable.Status
	22, // 18: grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.interval:type_name -> google.type.Interval
	3,  // 19: grpc.tradeapi.v1.assets.AssetsService.Exchanges:input_type -> grpc.tradeapi.v1.assets.ExchangesRequest
	5,  // 20: grpc.tradeapi.v1.assets.AssetsService.Assets:input_type -> grpc.tradeapi.v1.assets.AssetsRequest
	7,  // 21: grpc.tradeapi.v1.assets.AssetsService.GetAssetParams:input_type -> grpc.tradeapi.v1.assets.GetAssetParamsRequest
	9,  // 22: grpc.tradeapi.v1.assets.AssetsService.OptionsChain:input_type -> grpc.tradeapi.v1.assets.OptionsChainRequest
	11, // 23: grpc.tradeapi.v1.assets.AssetsService.Schedule:input_type -> grpc.tradeapi.v1.assets.ScheduleRequest
	4,  // 24: grpc.tradeapi.v1.assets.AssetsService.Exchanges:output_type -> grpc.tradeapi.v1.assets.ExchangesResponse
	6,  // 25: grpc.tradeapi.v1.assets.AssetsService.Assets:output_type -> grpc.tradeapi.v1.assets.AssetsResponse
	8,  // 26: grpc.tradeapi.v1.assets.AssetsService.GetAssetParams:output_type -> grpc.tradeapi.v1.assets.GetAssetParamsResponse
	10, // 27: grpc.tradeapi.v1.assets.AssetsService.OptionsChain:output_type -> grpc.tradeapi.v1.assets.OptionsChainResponse
	12, // 28: grpc.tradeapi.v1.assets.AssetsService.Schedule:output_type -> grpc.tradeapi.v1.assets.ScheduleResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_grpc_tradeapi_v1_assets_assets_service_proto_init() }
func file_grpc_tradeapi_v1_assets_assets_service_proto_init() {
	if File_grpc_tradeapi_v1_assets_assets_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssetParamsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssetParamsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionsChainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionsChainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exchange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Longable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shortable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleResponse_Sessions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_tradeapi_v1_assets_assets_service_proto_goTypes,
		DependencyIndexes: file_grpc_tradeapi_v1_assets_assets_service_proto_depIdxs,
		EnumInfos:         file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes,
		MessageInfos:      file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes,
	}.Build()
	File_grpc_tradeapi_v1_assets_assets_service_proto = out.File
	file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc = nil
	file_grpc_tradeapi_v1_assets_assets_service_proto_goTypes = nil
	file_grpc_tradeapi_v1_assets_assets_service_proto_depIdxs = nil
}
